spring:
    social:
        twitter:
            app-id: yix4Ai9xDbWBKV3yFPFGs8Nkf
            app-secret: 9rXtdeYe5v3wmGR5E96ubiXRDeWzZFgRt2ZYdgSKeQFivw0OtD
    data:
        mongodb:
            # host: localhost
            # port: 27017
            database: twitties